const NBA_LOGOS: Record<string, string> = {
  "Atlanta Hawks": "https://a.espncdn.com/i/teamlogos/nba/500/atl.png",
  "Boston Celtics": "https://a.espncdn.com/i/teamlogos/nba/500/bos.png",
  "Brooklyn Nets": "https://a.espncdn.com/i/teamlogos/nba/500/bkn.png",
  "Charlotte Hornets": "https://a.espncdn.com/i/teamlogos/nba/500/cha.png",
  "Chicago Bulls": "https://a.espncdn.com/i/teamlogos/nba/500/chi.png",
  "Cleveland Cavaliers": "https://a.espncdn.com/i/teamlogos/nba/500/cle.png",
  "Dallas Mavericks": "https://a.espncdn.com/i/teamlogos/nba/500/dal.png",
  "Denver Nuggets": "https://a.espncdn.com/i/teamlogos/nba/500/den.png",
  "Detroit Pistons": "https://a.espncdn.com/i/teamlogos/nba/500/det.png",
  "Golden State Warriors": "https://a.espncdn.com/i/teamlogos/nba/500/gs.png",
  "Houston Rockets": "https://a.espncdn.com/i/teamlogos/nba/500/hou.png",
  "Indiana Pacers": "https://a.espncdn.com/i/teamlogos/nba/500/ind.png",
  "LA Clippers": "https://a.espncdn.com/i/teamlogos/nba/500/lac.png",
  "Los Angeles Lakers": "https://a.espncdn.com/i/teamlogos/nba/500/lal.png",
  "Memphis Grizzlies": "https://a.espncdn.com/i/teamlogos/nba/500/mem.png",
  "Miami Heat": "https://a.espncdn.com/i/teamlogos/nba/500/mia.png",
  "Milwaukee Bucks": "https://a.espncdn.com/i/teamlogos/nba/500/mil.png",
  "Minnesota Timberwolves": "https://a.espncdn.com/i/teamlogos/nba/500/min.png",
  "New Orleans Pelicans": "https://a.espncdn.com/i/teamlogos/nba/500/no.png",
  "New York Knicks": "https://a.espncdn.com/i/teamlogos/nba/500/ny.png",
  "Oklahoma City Thunder": "https://a.espncdn.com/i/teamlogos/nba/500/okc.png",
  "Orlando Magic": "https://a.espncdn.com/i/teamlogos/nba/500/orl.png",
  "Philadelphia 76ers": "https://a.espncdn.com/i/teamlogos/nba/500/phi.png",
  "Phoenix Suns": "https://a.espncdn.com/i/teamlogos/nba/500/phx.png",
  "Portland Trail Blazers": "https://a.espncdn.com/i/teamlogos/nba/500/por.png",
  "Sacramento Kings": "https://a.espncdn.com/i/teamlogos/nba/500/sac.png",
  "San Antonio Spurs": "https://a.espncdn.com/i/teamlogos/nba/500/sa.png",
  "Toronto Raptors": "https://a.espncdn.com/i/teamlogos/nba/500/tor.png",
  "Utah Jazz": "https://a.espncdn.com/i/teamlogos/nba/500/utah.png",
  "Washington Wizards": "https://a.espncdn.com/i/teamlogos/nba/500/wsh.png",
};

const NHL_LOGOS: Record<string, string> = {
  "Anaheim Ducks": "https://a.espncdn.com/i/teamlogos/nhl/500/ana.png",
  "Boston Bruins": "https://a.espncdn.com/i/teamlogos/nhl/500/bos.png",
  "Buffalo Sabres": "https://a.espncdn.com/i/teamlogos/nhl/500/buf.png",
  "Calgary Flames": "https://a.espncdn.com/i/teamlogos/nhl/500/cgy.png",
  "Carolina Hurricanes": "https://a.espncdn.com/i/teamlogos/nhl/500/car.png",
  "Chicago Blackhawks": "https://a.espncdn.com/i/teamlogos/nhl/500/chi.png",
  "Colorado Avalanche": "https://a.espncdn.com/i/teamlogos/nhl/500/col.png",
  "Columbus Blue Jackets": "https://a.espncdn.com/i/teamlogos/nhl/500/cbj.png",
  "Dallas Stars": "https://a.espncdn.com/i/teamlogos/nhl/500/dal.png",
  "Detroit Red Wings": "https://a.espncdn.com/i/teamlogos/nhl/500/det.png",
  "Edmonton Oilers": "https://a.espncdn.com/i/teamlogos/nhl/500/edm.png",
  "Florida Panthers": "https://a.espncdn.com/i/teamlogos/nhl/500/fla.png",
  "Los Angeles Kings": "https://a.espncdn.com/i/teamlogos/nhl/500/la.png",
  "Minnesota Wild": "https://a.espncdn.com/i/teamlogos/nhl/500/min.png",
  "Montreal Canadiens": "https://a.espncdn.com/i/teamlogos/nhl/500/mtl.png",
  "Nashville Predators": "https://a.espncdn.com/i/teamlogos/nhl/500/nsh.png",
  "New Jersey Devils": "https://a.espncdn.com/i/teamlogos/nhl/500/nj.png",
  "New York Islanders": "https://a.espncdn.com/i/teamlogos/nhl/500/nyi.png",
  "New York Rangers": "https://a.espncdn.com/i/teamlogos/nhl/500/nyr.png",
  "Ottawa Senators": "https://a.espncdn.com/i/teamlogos/nhl/500/ott.png",
  "Philadelphia Flyers": "https://a.espncdn.com/i/teamlogos/nhl/500/phi.png",
  "Pittsburgh Penguins": "https://a.espncdn.com/i/teamlogos/nhl/500/pit.png",
  "San Jose Sharks": "https://a.espncdn.com/i/teamlogos/nhl/500/sj.png",
  "Seattle Kraken": "https://a.espncdn.com/i/teamlogos/nhl/500/sea.png",
  "St. Louis Blues": "https://a.espncdn.com/i/teamlogos/nhl/500/stl.png",
  "Tampa Bay Lightning": "https://a.espncdn.com/i/teamlogos/nhl/500/tb.png",
  "Toronto Maple Leafs": "https://a.espncdn.com/i/teamlogos/nhl/500/tor.png",
  "Utah Mammoth": "https://a.espncdn.com/i/teamlogos/nhl/500/utah.png",
  "Vancouver Canucks": "https://a.espncdn.com/i/teamlogos/nhl/500/van.png",
  "Vegas Golden Knights": "https://a.espncdn.com/i/teamlogos/nhl/500/vgk.png",
  "Washington Capitals": "https://a.espncdn.com/i/teamlogos/nhl/500/wsh.png",
  "Winnipeg Jets": "https://a.espncdn.com/i/teamlogos/nhl/500/wpg.png",
};

const FOOTBALL_LOGOS: Record<string, string> = {
  // Premier League
  "AFC Bournemouth": "https://a.espncdn.com/i/teamlogos/soccer/500/349.png",
  "Arsenal": "https://a.espncdn.com/i/teamlogos/soccer/500/359.png",
  "Aston Villa": "https://a.espncdn.com/i/teamlogos/soccer/500/362.png",
  "Brentford": "https://a.espncdn.com/i/teamlogos/soccer/500/337.png",
  "Brighton & Hove Albion": "https://a.espncdn.com/i/teamlogos/soccer/500/331.png",
  "Burnley": "https://a.espncdn.com/i/teamlogos/soccer/500/379.png",
  "Chelsea": "https://a.espncdn.com/i/teamlogos/soccer/500/363.png",
  "Crystal Palace": "https://a.espncdn.com/i/teamlogos/soccer/500/384.png",
  "Everton": "https://a.espncdn.com/i/teamlogos/soccer/500/368.png",
  "Fulham": "https://a.espncdn.com/i/teamlogos/soccer/500/370.png",
  "Leeds United": "https://a.espncdn.com/i/teamlogos/soccer/500/357.png",
  "Liverpool": "https://a.espncdn.com/i/teamlogos/soccer/500/364.png",
  "Manchester City": "https://a.espncdn.com/i/teamlogos/soccer/500/382.png",
  "Manchester United": "https://a.espncdn.com/i/teamlogos/soccer/500/360.png",
  "Newcastle United": "https://a.espncdn.com/i/teamlogos/soccer/500/361.png",
  "Nottingham Forest": "https://a.espncdn.com/i/teamlogos/soccer/500/393.png",
  "Sunderland": "https://a.espncdn.com/i/teamlogos/soccer/500/366.png",
  "Tottenham Hotspur": "https://a.espncdn.com/i/teamlogos/soccer/500/367.png",
  "West Ham United": "https://a.espncdn.com/i/teamlogos/soccer/500/371.png",
  "Wolverhampton Wanderers": "https://a.espncdn.com/i/teamlogos/soccer/500/380.png",
  // La Liga
  "Alavés": "https://a.espncdn.com/i/teamlogos/soccer/500/96.png",
  "Athletic Club": "https://a.espncdn.com/i/teamlogos/soccer/500/93.png",
  "Atlético Madrid": "https://a.espncdn.com/i/teamlogos/soccer/500/1068.png",
  "Barcelona": "https://a.espncdn.com/i/teamlogos/soccer/500/83.png",
  "Celta Vigo": "https://a.espncdn.com/i/teamlogos/soccer/500/85.png",
  "Elche": "https://a.espncdn.com/i/teamlogos/soccer/500/3751.png",
  "Espanyol": "https://a.espncdn.com/i/teamlogos/soccer/500/88.png",
  "Getafe": "https://a.espncdn.com/i/teamlogos/soccer/500/2922.png",
  "Girona": "https://a.espncdn.com/i/teamlogos/soccer/500/9812.png",
  "Levante": "https://a.espncdn.com/i/teamlogos/soccer/500/1538.png",
  "Mallorca": "https://a.espncdn.com/i/teamlogos/soccer/500/84.png",
  "Osasuna": "https://a.espncdn.com/i/teamlogos/soccer/500/97.png",
  "Rayo Vallecano": "https://a.espncdn.com/i/teamlogos/soccer/500/101.png",
  "Real Betis": "https://a.espncdn.com/i/teamlogos/soccer/500/244.png",
  "Real Madrid": "https://a.espncdn.com/i/teamlogos/soccer/500/86.png",
  "Real Oviedo": "https://a.espncdn.com/i/teamlogos/soccer/500/92.png",
  "Real Sociedad": "https://a.espncdn.com/i/teamlogos/soccer/500/89.png",
  "Sevilla": "https://a.espncdn.com/i/teamlogos/soccer/500/243.png",
  "Valencia": "https://a.espncdn.com/i/teamlogos/soccer/500/94.png",
  "Villarreal": "https://a.espncdn.com/i/teamlogos/soccer/500/102.png",
  // Bundesliga
  "1. FC Heidenheim 1846": "https://a.espncdn.com/i/teamlogos/soccer/500/6418.png",
  "1. FC Union Berlin": "https://a.espncdn.com/i/teamlogos/soccer/500/598.png",
  "Bayer Leverkusen": "https://a.espncdn.com/i/teamlogos/soccer/500/131.png",
  "Bayern Munich": "https://a.espncdn.com/i/teamlogos/soccer/500/132.png",
  "Borussia Dortmund": "https://a.espncdn.com/i/teamlogos/soccer/500/124.png",
  "Borussia Mönchengladbach": "https://a.espncdn.com/i/teamlogos/soccer/500/268.png",
  "Eintracht Frankfurt": "https://a.espncdn.com/i/teamlogos/soccer/500/125.png",
  "FC Augsburg": "https://a.espncdn.com/i/teamlogos/soccer/500/3841.png",
  "FC Cologne": "https://a.espncdn.com/i/teamlogos/soccer/500/122.png",
  "Hamburg SV": "https://a.espncdn.com/i/teamlogos/soccer/500/127.png",
  "Mainz": "https://a.espncdn.com/i/teamlogos/soccer/500/2950.png",
  "RB Leipzig": "https://a.espncdn.com/i/teamlogos/soccer/500/11420.png",
  "SC Freiburg": "https://a.espncdn.com/i/teamlogos/soccer/500/126.png",
  "St. Pauli": "https://a.espncdn.com/i/teamlogos/soccer/500/270.png",
  "TSG Hoffenheim": "https://a.espncdn.com/i/teamlogos/soccer/500/7911.png",
  "VfB Stuttgart": "https://a.espncdn.com/i/teamlogos/soccer/500/134.png",
  "VfL Wolfsburg": "https://a.espncdn.com/i/teamlogos/soccer/500/138.png",
  "Werder Bremen": "https://a.espncdn.com/i/teamlogos/soccer/500/137.png",
  // Serie A
  "AC Milan": "https://a.espncdn.com/i/teamlogos/soccer/500/103.png",
  "AS Roma": "https://a.espncdn.com/i/teamlogos/soccer/500/104.png",
  "Atalanta": "https://a.espncdn.com/i/teamlogos/soccer/500/105.png",
  "Bologna": "https://a.espncdn.com/i/teamlogos/soccer/500/107.png",
  "Cagliari": "https://a.espncdn.com/i/teamlogos/soccer/500/2925.png",
  "Como": "https://a.espncdn.com/i/teamlogos/soccer/500/2572.png",
  "Cremonese": "https://a.espncdn.com/i/teamlogos/soccer/500/4050.png",
  "Fiorentina": "https://a.espncdn.com/i/teamlogos/soccer/500/109.png",
  "Genoa": "https://a.espncdn.com/i/teamlogos/soccer/500/3263.png",
  "Hellas Verona": "https://a.espncdn.com/i/teamlogos/soccer/500/119.png",
  "Internazionale": "https://a.espncdn.com/i/teamlogos/soccer/500/110.png",
  "Juventus": "https://a.espncdn.com/i/teamlogos/soccer/500/111.png",
  "Lazio": "https://a.espncdn.com/i/teamlogos/soccer/500/112.png",
  "Lecce": "https://a.espncdn.com/i/teamlogos/soccer/500/113.png",
  "Napoli": "https://a.espncdn.com/i/teamlogos/soccer/500/114.png",
  "Parma": "https://a.espncdn.com/i/teamlogos/soccer/500/115.png",
  "Pisa": "https://a.espncdn.com/i/teamlogos/soccer/500/3956.png",
  "Sassuolo": "https://a.espncdn.com/i/teamlogos/soccer/500/3997.png",
  "Torino": "https://a.espncdn.com/i/teamlogos/soccer/500/239.png",
  "Udinese": "https://a.espncdn.com/i/teamlogos/soccer/500/118.png",
  // Ligue 1
  "AJ Auxerre": "https://a.espncdn.com/i/teamlogos/soccer/500/172.png",
  "AS Monaco": "https://a.espncdn.com/i/teamlogos/soccer/500/174.png",
  "Angers": "https://a.espncdn.com/i/teamlogos/soccer/500/7868.png",
  "Brest": "https://a.espncdn.com/i/teamlogos/soccer/500/6997.png",
  "Le Havre AC": "https://a.espncdn.com/i/teamlogos/soccer/500/3236.png",
  "Lens": "https://a.espncdn.com/i/teamlogos/soccer/500/175.png",
  "Lille": "https://a.espncdn.com/i/teamlogos/soccer/500/166.png",
  "Lorient": "https://a.espncdn.com/i/teamlogos/soccer/500/273.png",
  "Lyon": "https://a.espncdn.com/i/teamlogos/soccer/500/167.png",
  "Marseille": "https://a.espncdn.com/i/teamlogos/soccer/500/176.png",
  "Metz": "https://a.espncdn.com/i/teamlogos/soccer/500/177.png",
  "Nantes": "https://a.espncdn.com/i/teamlogos/soccer/500/165.png",
  "Nice": "https://a.espncdn.com/i/teamlogos/soccer/500/2502.png",
  "Paris FC": "https://a.espncdn.com/i/teamlogos/soccer/500/6851.png",
  "Paris Saint-Germain": "https://a.espncdn.com/i/teamlogos/soccer/500/160.png",
  "Stade Rennais": "https://a.espncdn.com/i/teamlogos/soccer/500/169.png",
  "Strasbourg": "https://a.espncdn.com/i/teamlogos/soccer/500/180.png",
  "Toulouse": "https://a.espncdn.com/i/teamlogos/soccer/500/179.png",
  // Champions League (teams not in domestic leagues above)
  "Ajax Amsterdam": "https://a.espncdn.com/i/teamlogos/soccer/500/139.png",
  "Benfica": "https://a.espncdn.com/i/teamlogos/soccer/500/1929.png",
  "Bodo/Glimt": "https://a.espncdn.com/i/teamlogos/soccer/500/2980.png",
  "Club Brugge": "https://a.espncdn.com/i/teamlogos/soccer/500/570.png",
  "F.C. København": "https://a.espncdn.com/i/teamlogos/soccer/500/909.png",
  "FK Qarabag": "https://a.espncdn.com/i/teamlogos/soccer/500/10414.png",
  "Galatasaray": "https://a.espncdn.com/i/teamlogos/soccer/500/432.png",
  "Kairat Almaty": "https://a.espncdn.com/i/teamlogos/soccer/500/2528.png",
  "Olympiacos": "https://a.espncdn.com/i/teamlogos/soccer/500/435.png",
  "PSV Eindhoven": "https://a.espncdn.com/i/teamlogos/soccer/500/148.png",
  "Pafos": "https://a.espncdn.com/i/teamlogos/soccer/500/22281.png",
  "Slavia Prague": "https://a.espncdn.com/i/teamlogos/soccer/500/494.png",
  "Sporting CP": "https://a.espncdn.com/i/teamlogos/soccer/500/2250.png",
  "Union St.-Gilloise": "https://a.espncdn.com/i/teamlogos/soccer/500/5807.png",
};

export function getTeamLogo(
  sport: "football" | "nba" | "nhl",
  teamName: string,
): string | undefined {
  switch (sport) {
    case "nba":
      return NBA_LOGOS[teamName];
    case "nhl":
      return NHL_LOGOS[teamName];
    case "football":
      return FOOTBALL_LOGOS[teamName];
  }
}
